version: '3'
services:
  web:
    build: .
    ports:
      - '3333:3333'
    volumes: 
        - .:app/
    depends_on: 
        - postgres
  db_development:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports: 
      - '3334':'5432' 
  postgres:
    image: postgres:alpine
    restart: on-failure
    volumes: /var/lib/postgresql/data
    env_file:
      - production.env
    ports: 
      - '5432':'5432'
